name: Notificar Push a Main

on:
  push:
    branches: [ main ]

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Enviar notificación HTTP
        run: |
          curl -X POST -H "Content-Type: text/plain" \
          -d "🚨 El usuario ${{ github.actor }} hizo push a la rama main. Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}" \
          https://ntfy.sh/devops-itla
